---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gudexams-pv-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 55Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gudexams-public-data
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/public-data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gudexams-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: gudexams
  replicas: 5
  template:
    metadata:
      labels:
        app: gudexams
    spec:
      containers:
      - name: pods-gudexams-deployment
        image: 056121157689.dkr.ecr.ap-south-1.amazonaws.com/gudexams:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/var/www/html/public/data"
          name: gudexams-public-data
      volumes:
        - name: gudexams-public-data
          persistentVolumeClaim:
            claimName: gudexams-pv-claim
---
apiVersion: v1
kind: Service
metadata:
    name: gudexams-service
    namespace: dev
spec:
  selector:
    app: gudexams
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gudexams-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  tls:
  - secretName: online-gudexams-in-tls
    hosts:
    - online.gudexams.in
  rules:
  - host: ad46a96d2a9f7462f85a1b20b20e9e31-1240663445.ap-south-1.elb.amazonaws.com
    http:
      paths:
      - backend:
          service:
           name: gudexams-service
           port:
             number: 80
        path: /
        pathType: Prefix
  - host: online.gudexams.in
    http:
      paths:
      - backend:
          service:
           name: gudexams-service
           port:
             number: 80
        path: /
        pathType: Prefix
