---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gudexams-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: gudexams
  replicas: 30
  template:
    metadata:
      labels:
        app: gudexams
    spec:
      containers:
      - name: pods-gudexams-deployment
        image: 056121157689.dkr.ecr.ap-south-1.amazonaws.com/gudexams:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "3Gi"
            cpu: "1600m"
          limits:
            memory: "3Gi"
            cpu: "1800m"
        volumeMounts:
         - name: gudexams-production-data
           mountPath: "/var/www/html/public/data"
        env:
        - name: PROVISIONER_NAME
          value: efs-storage
        - name: NFS_SERVER
          value: 192.168.250.251
        - name: NFS_PATH
          value: /
      volumes:
      - name: gudexams-production-data
        nfs:
          server: 192.168.250.251
          path: /
---
apiVersion: v1
kind: Service
metadata:
    name: gudexams-service
    namespace: dev
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:056121157689:certificate/4c9f4c8c-9e81-4885-b477-9ee182463725
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: gudexams
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gudexams-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  tls:
    - secretName: gudexams-com-tls
      hosts:
      - online.gudexams.com
  rules:
  - host: ad46a96d2a9f7462f85a1b20b20e9e31-1240663445.ap-south-1.elb.amazonaws.com
    http:
      paths:
      - backend:
          service:
           name: gudexams-service
           port:
             number: 443
        path: /
        pathType: Prefix
  - host: online.gudexams.com
    http:
      paths:
      - backend:
          service:
           name: gudexams-service
           port:
             number: 443
        path: /
        pathType: Prefix
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gudexams-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gudexams-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
